spring:
  cloud:
    stream:
      bindings:
        order-input-channel:
          destination: user
        order-home-output-channel:
          destination: domicile-service
        order-takeaway-output-channel:
          destination: emporter-service
      kafka:
        streams:
          binder:
            brokers: localhost:9092